### ISSUE TITLE
port

### ISSUE THREAD

**Issue by jcx1989** [xuehy/pytorch-maddpg#1]
i use  a port 8097 instead of the 5274.because if i use the 5074,connect error.i want to know why,please.

**Comment by xuehy** [comment]
Are you sure that your port 5274 is not in use?

**Comment by jcx1989** [comment]
error is ：requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5274): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2d61c4cef0>: Failed to establish a new connection: [Errno 111] Connection refused',))
thanks！

**Comment by xuehy** [comment]
The reason may be that you have not started a visdom server. Please refer to your another issue.
