### ISSUE TITLE
Negative actor losses

### ISSUE THREAD

**Issue by richielo** [xuehy/pytorch-maddpg#10]
I am sorry if this is a stupid question. I have been getting negative losses for the actors. Is this normal? If not, how should I interpret it? 

Thanks!

**Comment by xuehy** [comment]
Can you show me your loss curves for the actors?

**Comment by richielo** [comment]
I am actually trying to adapt your code to another visual domain, so it may take me a bit to reproduce the loss curve. I simply added up the actor losses to compute an average actor loss per epoch. It just goes below zero after a certain point without changing any of the learning code, which does not make any sense to me

**Comment by xuehy** [comment]
Since the actor loss is just the negative of Q value, so it is normal to get negative losses.
