### ISSUE TITLE
有关网络结构的提问

### ISSUE THREAD

**Issue by DKuan** [xuehy/pytorch-maddpg#13]
看您这边个人介绍是在网易，所以直接中文提问了。有下面三个问题不是很清楚，麻烦您有时间解答一下：
1、为什么critic的网络结构是先把obs观测值升高到1024？
2、直接与原始的action变量进行拼接，而不是通过一次全连接变换？
3、我测试了不升高obs的维度，即尝试((obs->256)+action)->128->64，结果也表现较好，这里有相应解释吗？

**Comment by xuehy** [comment]
个人觉得对于这种比较简单的任务，这种网络结构上的东西应该不太要紧。


发件人: Zachary<mailto:notifications@github.com>
发送时间: 2020年1月5日 21:42
收件人: xuehy/pytorch-maddpg<mailto:pytorch-maddpg@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [xuehy/pytorch-maddpg] 有关网络结构的提问 (#13)


看您这边个人介绍是在网易，所以直接中文提问了。有下面三个问题不是很清楚，麻烦您有时间解答一下：
1、为什么critic的网络结构是先把obs观测值升高到1024？
2、直接与原始的action变量进行拼接，而不是通过一次全连接变换？
3、我测试了不升高obs的维度，即尝试((obs->256)+action)->128->64，结果也表现较好，这里有相应解释吗？

―

**Comment by DKuan** [comment]
好的，谢谢回复~
