### ISSUE TITLE
regarding to policies and reward functions

### ISSUE THREAD

**Issue by zyzhang1130** [xuehy/pytorch-maddpg#14]
Hi,
May I ask how do you define more than one policy and reward function concurrently in a multi-agent setting?
Thank you.

**Comment by xuehy** [comment]
You can find the reward details in [pursuit/waterworld_modified.py](https://github.com/xuehy/pytorch-maddpg/blob/master/pursuit/waterworld_modified.py).

For the policy, check [MADDPG.py ](https://github.com/xuehy/pytorch-maddpg/blob/master/MADDPG.py).
