### ISSUE TITLE
show

### ISSUE THREAD

**Issue by jcx1989** [xuehy/pytorch-maddpg#2]
hello,i have already run this program,but not show the picture,is because i did not install opencv?or any problems?the picture shows on the browser？
thanks！

**Comment by xuehy** [comment]
You need to start a visdom server before running the code. Please refer to **[Visdom](https://github.com/facebookresearch/visdom)**  for the usage of visdom.

**Comment by hellooolleh** [comment]
Sorry, but I had already opened a visdom server, it was  blue and didn't show anything. Is there any other problems?
Thanks!

**Comment by hellooolleh** [comment]
Sorry , but I had already opened a visdom server, it was blue and didn't show anything. Is there any problems?
Thanks!

**Comment by hellooolleh** [comment]
Sorry , but I had already opened a visdom server, it was blue and didn't show anything. Is there any problems?
Thanks!

**Comment by xuehy** [comment]
@hellooolleh Some javescripts of the visdom server may have not loaded correctly. You can check with the tools for web developers of Chrome or other browsers to see the missing parts. 

As far as I know, it always happens in mainland China. A way to circumvent is to download the missing javascripts to your visdom installation dir and modify the visdom main page template.

You may refer to [visdom shows nothing](https://github.com/facebookresearch/visdom/issues/111#issuecomment-321743890).

**Comment by hellooolleh** [comment]
@xuehy , Ok, I will have a try. Thanks!
