### ISSUE TITLE
gif problem

### ISSUE THREAD

**Issue by jcx1989** [xuehy/pytorch-maddpg#3]
hello!i have already set up the environment,and trainned to 20  episode.I see two pane on the visdom,but not see the gif(two balls find other balls in the gif),why?

**Comment by xuehy** [comment]
Have you set `e_render = True` in main.py ?
Besides, the images will be rendered every 100 episodes. You can modify this interval in main.py:

`if i_episode % 100 == 0 and e_render:`

**Comment by jcx1989** [comment]
hello!when the episode is more than 100,the terminal printf Killed，and the program is over,why?

**Comment by xuehy** [comment]
Make sure you have opencv installed with the python support.
