### ISSUE TITLE
no positive reward

### ISSUE THREAD

**Issue by Kyle1993** [xuehy/pytorch-maddpg#7]
When the  blue ball hits the green ball does not get a positive reward, and the green ball does not disappear? is't correct?

**Comment by xuehy** [comment]
The green ball will disappear and re-appear at different locations. The reward can be set in the code while by default is +10.

**Comment by Kyle1993** [comment]
I just run a simple rendered env with a random-action Agent, the env never return positive reward, even though I can see the blue ball through green ball. here is my simple code, if the parameter is correct?(I replaced the original pursuit folder with the same one in your project)

```
from madrl_environments.pursuit import MAWaterWorld_mod
import numpy as np
import time

food_reward = 10.
poison_reward = -1.
encounter_reward = 0.01
n_coop = 2

n_pursuers = 1
n_evaders = 50
n_poison = 5
world = MAWaterWorld_mod(n_pursuers=n_pursuers, n_evaders=n_evaders,
                         n_poison=n_poison, obstacle_radius=0.04,
                         food_reward=food_reward,
                         poison_reward=poison_reward,
                         encounter_reward=encounter_reward,
                         n_coop=n_coop,
                         sensor_range=0.2, obstacle_loc=None, )

n_episode = 200
max_steps = 1000
for i_episode in range(n_episode):
    obs = world.reset()
    for t in range(max_steps):
        world.render()
        action = np.random.uniform(-1,1,(n_pursuers,2))
        obs_, reward, done, _ = world.step(action)
        print(reward)
        time.sleep(0.3)
```

**Comment by xuehy** [comment]
The green ball will disappear if and only if hit simultaneously by two agents and the corresponding reward is 10. If only a single agent hit the green ball, the ball will not disappear and the reward will be 0.01.

**Comment by Kyle1993** [comment]
wow, thanks so much

**Comment by Kyle1993** [comment]
I have another problem, is there any detail introduction about the (213,) state?

**Comment by xuehy** [comment]
Perhaps you'll have to read the code in `pursuit/waterworld_modified.py`.  Starting from line 311.

**Comment by Kyle1993** [comment]
ok, thanks so much

**Comment by Kyle1993** [comment]
if n_agent > 2, the positive reward will get when 2 agents hit green simultaneously? or all agent hit simultaneously

**Comment by xuehy** [comment]
The cooperation capacity can be passed to the `n_coop` of the environment's constructor. You can set it to any positive integer you like. See line 15 in `main.py`
