### ISSUE TITLE
Updating policy issue

### ISSUE THREAD

**Issue by ZishunYu** [xuehy/pytorch-maddpg#8]
Hello,

I encountered an issue when I try to run your code. I tried to find why it occurs but have no clue yet. 
Could you please take a look the error below? Appreciate.  

Traceback (most recent call last):

  File "<ipython-input-1-fdc860125727>", line 1, in <module>
    runfile('/home/zishun/pytorch-maddpg-master/main.py', wdir='/home/zishun/pytorch-maddpg-master')

  File "/home/zishun/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/zishun/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/zishun/pytorch-maddpg-master/main.py", line 83, in <module>
    c_loss, a_loss = maddpg.update_policy()

  File "/home/zishun/pytorch-maddpg-master/MADDPG.py", line 111, in update_policy
    self.n_agents * self.n_actions))

RuntimeError: expand(torch.FloatTensor{[999, 1]}, size=[999]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)

**Comment by ZishunYu** [comment]
It seems the problem is at forwarding, 

            target_Q[non_final_mask] = self.critics_target[agent](
                non_final_next_states.view(-1, self.n_agents * self.n_states),
                non_final_next_actions.view(-1, self.n_agents * self.n_actions))

I am not sure whether it is caused by the unmatched size of _non_final_mask_  and _states&actions_
mask size, torch.Size([1000])
state size, torch.Size([999, 426])
action size, torch.Size([999, 4])

**Comment by xuehy** [comment]
This is strange. The size doesn't matter since the mask should make the target_Q to the same size as the right-hand side. Currently I cannot reproduce your error. I'll keep an eye on your problem. Maybe you can offer more details.

**Comment by xuehy** [comment]
Aha. I find it. This is because of pytorch 0.4.0's new broadcasting rule. Bug fixed. You can download the new code.

**Comment by ZishunYu** [comment]
Thanks a lot, it works perfectly now.
