### ISSUE TITLE
MultiGPU training 

### ISSUE THREAD

**Issue by richielo** [xuehy/pytorch-maddpg#9]
Thanks for the great work. Do you think the training can be sped up if we use multiple gpu / some form of parallel training in the update policy part instead of looping through the agent one by one? If so, what kind of approach would you suggest in doing so? 

Thanks again

**Comment by xuehy** [comment]
I think acceleration via parallelization is possible. Maybe just distribute the agents on different GPUs? Communications between different GPUs may be important. I cannot try since I don't have multiple GPUs at hand.

**Comment by richielo** [comment]
ill give that a try. Thanks!

**Comment by ff0kk** [comment]
> ill give that a try. Thanks!

Hi! Have you managed to implement it on different GPUs? I have some problems to consult you. Is it possible to use the DistributedDataParallel(DDP) class with MADDPG? Thanks!
